export const NAVIGATION_PAGES = {
    BUYER_HOME: 'BUYER_HOME',
    BUYER_SEARCH: 'BUYER_SEARCH',
    BUYER_SEARCHRESULTS: 'BUYER_SEARCHRESULTS',
    BUYER_COMPANYNAME: 'BUYER_COMPANYNAME',
    BUYER_PROJECTS: 'BUYER_PROJECTS',
    BUYER_PROJECT_DETAILS: 'BUYER_PROJECT_DETAILS',
    BUYER_PROJECT_SEARCH: 'BUYER_PROJECT_SEARCH',

    SUPPLIER_HOME: 'SUPPLIER_HOME',
    SUPPLIER_SUMMARY: 'SUPPLIER_SUMMARY',
    SUPPLIER_UNSPSC: 'SUPPLIER_UNSPSC',
    SUPPLIER_CPV: 'SUPPLIER_CPV',
    SUPPLIER_NACE: 'SUPPLIER_NACE',
    SUPPLIER_MARKET: 'SUPPLIER_MARKET',

    SELLER_HOME: 'SELLER_HOME',
    SELLER_GET_NOTIFIED: 'SELLER_GET_NOTIFIED',
    SELLER_MATCHING_TENDERS: 'SELLER_MATCHING_TENDERS',
    SELLER_GLOBAL_TENDER: 'SELLER_GLOBAL_TENDER',
    SELLER_TENDER_DETAILS: 'SELLER_TENDER_DETAILS',

    ADMIN_TEMPLATES: 'ADMIN_TEMPLATES',
    ALL_USERS: 'ALL_USERS',
    ALL_USER_DETAILS: 'ALL_USER_DETAILS',
    E_CONNECT_HOME: 'E_CONNECT_HOME',
    COMMUNICATIONS: 'COMMUNICATIONS',
    COMMUNICATIONS_LOG: 'COMMUNICATIONS_LOG',
    COMMUNICATIONS_BASKET: 'COMMUNICATIONS_BASKET',
    COMMUNICATIONS_BASKET_DETAILS: 'COMMUNICATIONS_BASKET_DETAILS',
    NEW_COMMUNICATION: 'NEW_COMMUNICATION',

    DRAWING_TOOL_HOME: 'DRAWING_TOOL_HOME',
    CHART_DRAWING: 'CHART_DRAWING',
    COLLECTION_DETAILS: 'COLLECTION_DETAILS',
    SURVEY_HOME: 'SURVEY_HOME',
    SURVEY_CREATE: 'SURVEY_CREATE',

};

export const ROUTES = {
    BUYER_HOME: '/Buyer',
    BUYER_SEARCH: '/Buyer/Search',
    BUYER_SEARCHRESULTS: '/Buyer/Search',
    BUYER_COMPANYNAME: '/Buyer/Search',
    BUYER_PROJECTS: '/Buyer/Projects',
    BUYER_PROJECT_DETAILS: '/Buyer/Projects',
    BUYER_PROJECT_SEARCH: '/Buyer/Projects/Search',

    SUPPLIER_HOME: '/Supplier',
    SUPPLIER_SUMMARY: '/Supplier/Summary',
    SUPPLIER_UNSPSC: '/Supplier/UNSPSC',
    SUPPLIER_CPV: '/Supplier/CPV',
    SUPPLIER_NACE: '/Supplier/NACE',
    SUPPLIER_MARKET: '/Supplier/Markets',

    SELLER_HOME: '/Seller',
    SELLER_GET_NOTIFIED: '/Seller/GetNotified',
    SELLER_MATCHING_TENDERS: '/Seller/MatchingTenders',
    SELLER_GLOBAL_TENDER: '/Seller/GolbalTenders',
    SELLER_TENDER_DETAILS: '/Seller/GolbalTenders',

    ADMIN_TEMPLATES: 'ADMIN_TEMPLATES',
    ALL_USERS: 'ALL_USERS',
    ALL_USER_DETAILS: 'ALL_USER_DETAILS',
    E_CONNECT_HOME: 'E_CONNECT_HOME',
    COMMUNICATIONS: 'COMMUNICATIONS',
    COMMUNICATIONS_LOG: 'COMMUNICATIONS_LOG',
    COMMUNICATIONS_BASKET: 'COMMUNICATIONS_BASKET',
    COMMUNICATIONS_BASKET_DETAILS: 'COMMUNICATIONS_BASKET_DETAILS',
    NEW_COMMUNICATION: 'NEW_COMMUNICATION',

    DRAWING_TOOL_HOME: 'DRAWING_TOOL_HOME',
    CHART_DRAWING: 'CHART_DRAWING',

};