export const NAVIGATION_PAGES = {
    BUYER_HOME: 'BUYER_HOME',
    BUYER_SEARCH: 'BUYER_SEARCH',
    BUYER_SEARCHRESULTS: 'SEARCH BUYER_SEARCHRESULTS',
    BUYER_COMPANYNAME: 'BUYER_COMPANYNAME',
    BUYER_PROJECTS: 'BUYER_PROJECTS',
    BUYER_PROJECT_DETAILS: 'BUYER_PROJECT_DETAILS',
    BUYER_PROJECT_SEARCH: 'BUYER_PROJECT_SEARCH',

    SUPPLIER_HOME: 'SUPPLIER_HOME',
    SUPPLIER_SUMMARY: 'SUPPLIER_SUMMARY',
    SUPPLIER_UNSPSC: 'SUPPLIER_UNSPSC',
    SUPPLIER_CPV: 'SUPPLIER_CPV',
    SUPPLIER_NACE: 'SUPPLIER_NACE',
    SUPPLIER_MARKET: 'SUPPLIER_MARKET',

    SELLER_HOME: 'SELLER_HOME',
    SELLER_GET_NOTIFIED: 'SELLER_GET_NOTIFIED',
    SELLER_MATCHING_TENDERS: 'SELLER_MATCHING_TENDERS',
    SELLER_GLOBAL_TENDER: 'SELLER_GLOBAL_TENDER',
};