export const NAVIGATION_PAGES = {
    BUYER_HOME: 'BUYER_HOME',
    BUYER_SEARCH: 'BUYER_SEARCH',
    BUYER_SEARCHRESULTS: 'SEARCH BUYER_SEARCHRESULTS',
    BUYER_COMPANYNAME: 'BUYER_COMPANYNAME',

    SUPPLIER_HOME: 'SUPPLIER_HOME',
    SUPPLIER_SUMMARY: 'SUPPLIER_SUMMARY',
    SUPPLIER_UNSPSC: 'SUPPLIER_UNSPSC',
    SUPPLIER_CPV: 'SUPPLIER_CPV',
    SUPPLIER_NACE: 'SUPPLIER_NACE',

};